name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_NOLOGO: true
    DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
    TERM: xterm

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test -c Release --no-build --output Detailed -- --coverage --coverage-output-format cobertura

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
    - name: Install MkDocs
      run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files
    - name: Validate docs
      run: mkdocs build --strict
